# -*- mode: ruby -*-
# vi: set ft=ruby :
 
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
 
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 77777, host: 77777 #Puerto por defecto para la app en modo dev
  config.vm.network "private_network", ip: "192.168.1.77"
  config.vm.synced_folder "htdocs", "/var/www/html" #local|vm !revisar!
  config.vm.provision "shell", path: "config.sh"
end
