# -*- mode: ruby -*-
# vi: set ft=ruby :
 
Vagrant.configure('2') do |config|
  config.vm.box = "ubuntu/trusty64" #v14
  config.vm.provider :virtualbox do |vb|
      vb.name = 'MEAN BOX (back/front)'
      vb.memory = 2048
      vb.cpus = 2
  end
  config.vm.network "forwarded_port", guest: 77777, host: 77777 #Puerto por defecto para la app en modo dev
  config.vm.network "private_network", ip: "192.168.1.77"
  config.vm.synced_folder "htdocs", "/var/www/html" #local|vm !revisar!
  config.vm.provision :puppet do |puppet|
     puppet.manifests_path = 'puppet/manifests'
     puppet.manifest_file = 'default.pp'
     puppet.options = [
      '--verbose',
      '--debug',
    ]
  end
end
