# -*- mode: ruby -*-
# vi: set ft=ruby :
 
Vagrant.configure('2') do |config|
  config.vm.box = "ubuntu/trusty64" #v14
  config.vm.provider :virtualbox do |vb|
      vb.name = 'meanbox'
      vb.memory = 512
      vb.cpus = 1
  end
  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end
  config.vm.network "forwarded_port", guest: 7777, host: 7777 #Puerto por defecto para la app en modo dev
  config.vm.network "private_network", ip: "192.168.2.77"
  config.vm.synced_folder "htdocs", "/var/www/html" #local|vm !revisar!
  
  config.vm.provision :shell do |shell|
   shell.inline = "mkdir -p /etc/puppet/modules;
                   puppet module install puppetlabs-apt;
                   puppet module install puppetlabs-git;
                   puppet module install puppetlabs-nodejs;
                   puppet module install puppetlabs-mongodb"
  end  
  config.vm.provision :puppet do |puppet|
     puppet.options = [
      '--verbose',
      '--debug',
    ]
  end
end
