# -*- mode: ruby -*-
# vi: set ft=ruby :
 
Vagrant.configure('2') do |config|
  config.vm.box = "ubuntu/trusty64" #v14
  config.vm.provider :virtualbox do |vb|
      vb.name = 'meanbox'
      vb.memory = 512
      vb.cpus = 1
  end
  config.vm.hostname = "arkbox"
  config.vm.post_up_message = "Perfecto! Ahora solo tienes que hacer 'vagrant ssh' para acceder, o entrar a mano via 127.0.0.1:2222"
  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end
  config.vm.network "forwarded_port", guest: 7777, host: 7777 #Puerto por defecto para la app en modo dev
  config.vm.network "forwarded_port", guest: 7333, host: 7333 #Puerto por defecto para la app en modo pro
  config.vm.network "private_network", ip: "192.168.7.77"
  config.vm.synced_folder "htdocs", "/var/www/html" #local|vm
    config.vm.synced_folder "htdocs", "/ome/vagrant/htdocs" #local|vm


  config.vm.provision :shell do |shell|
   shell.inline = "mkdir -p /etc/puppet/modules;
                   puppet module install puppetlabs-apt --force;
                   puppet module install puppetlabs-git --force;
                   puppet module install puppetlabs-mongodb --force;
                   puppet module install puppetlabs-ruby --force;
                   puppet module install puppetlabs-nodejs --force"
  end  
  config.vm.provision :puppet do |puppet|
     puppet.options = [
      #'--verbose',
      #'--debug',
    ]
  end
end
